apiVersion: batch/v1
kind: Job
metadata:
  name: ferb-latin-converter-job
spec:
  template:
    spec:
      containers:
      - name: ferb-latin-converter-job
        image: yash5090/ferb-latin-converter:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
