apiVersion: v1
kind: Service
metadata:
  name: ferb-latin-converter-service
spec:
  selector:
    app: ferb-latin-converter
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
